spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    url: jdbc\:mysql\://192.168.145.194\:3306/saiente?tuseUnicode\=true&characterEncoding\=utf-8&zeroDateTimeBehavior\=convertToNull
    username: root
    password: huatek
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20 
    max-idle: 8 
    min-idle: 8
    initial-size: 10
    max-lifetime: 100000000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0  
    jedis.pool.max-active: 50
    jedis.pool.max-wait: 3000
    jedis.pool.max-idle: 20
    jedis.pool.min-idle: 2
    timeout: 5000

mybatis:
  mapper-locations: classpath:com/antelope/framebase/mapping/**Mapper.xml

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

file:
  path: /app/files/
image:
  path: /app/images/
  url:
    prefix: https://127.0.0.1/images

log:
  db:
    driver: com.mysql.jdbc.Driver
    url: jdbc\:mysql\://192.168.145.194\:3306/saiente?tuseUnicode\=true&characterEncoding\=utf-8&zeroDateTimeBehavior\=convertToNull
    username: root
    password: huatek

login:
  url: open/v1.0/login/getUser
